data_dir: "data"
results_dir: "results"
pair_selection:
  lookback_days: 90
  coint_pvalue_threshold: 0.05
backtest:
  timeframe: "1d"
  rolling_window: 30
  zscore_threshold: 1.5
  fill_limit_pct: 0.2
