name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev
      - name: Ruff
        run: poetry run ruff check . --output-format=github
      - name: MyPy
        run: poetry run mypy src tests
      - name: Run pytest
        run: poetry run pytest
      - name: Bench rolling_beta
        run: echo "benchmark placeholder"
